# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2a7accbff53d7a7ea27180690b20cc792a1d9ddbe01508740f9d804d9c371bedd9413ff8c711cf4ee709173af96c77b59d72de33de2fc69830aa5e1a6ca6ede9

test:
  secret_key_base: 90ee674a918869b08f3aaf9ea185fa2c63bf9a6d3e774325cef7184ff41b9f47d3bf986d6468cae38bc9c0a535891a6e6df8796dbafb068c9ae02a735b4723ce

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
